/**
* This file is auto-generated by nestjs-proto-gen-ts
*/
import { Metadata } from '@grpc/grpc-js';

                export namespace common {
                                export interface Id {
                                    id?: string;
                                }
                                export interface Name {
                                    name?: string;
                                }
                                export interface Query {
                                    attributes?: string[];
                                    where?: string;
                                    order?: string;
                                    offset?: number;
                                    limit?: number;
                                }
                                export interface Count {
                                    count?: number;
                                }
                }
        
