/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace comments {
    export interface Comment {
        id?: string;
        organization?: string;
        comment?: string;
        created_at?: string;
        updated_at?: string;
    }
    export interface CreateCommentRequest {
        organization?: string;
        comment?: string;
    }
    export interface CommentList {
        data?: comments.Comment[];
    }
    export interface CommentsService {
        findAll(data: common.Query, metadata?: Metadata): Observable<CommentList>;
        // rpc count(common.Query) returns (common.Count){}
        create(data: CreateCommentRequest, metadata?: Metadata): Observable<Comment>;
    }
}
export namespace common {
    export interface Id {
        id?: string;
    }
    export interface Name {
        name?: string;
    }
    export interface Query {
        attributes?: string[];
        where?: string;
        order?: string;
        offset?: number;
        limit?: number;
    }
    export interface Count {
        count?: number;
    }
}

